FROM node:16-alpine

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package*.json .
RUN  npm ci

COPY . .

# COPY src ./src
# COPY public ./public
# COPY next.config.js .
# COPY tsconfig.json .
# COPY .env .