services:
  backend:
    container_name: openforms-backend
    image: biku1998/openforms-backend
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SIGN_SECRET=${SESSION_SIGN_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
    ports:
      - ${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}

  frontend:
    container_name: openforms-frontend
    image: biku1998/openforms-frontend
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}
    depends_on:
      - backend