services:
  database:
    container_name: postgres
    image: postgres:15
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'

  backend:
    container_name: openforms-backend-api
    image: biku1998/openforms-backend-api
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database
      - redis
