services:
  backend:
    container_name: openforms-backend
    image: biku1998/openforms-backend
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '${PORT:-3001}:${PORT:-3001}'

  frontend:
    container_name: openforms-frontend
    image: biku1998/openforms-frontend
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    build:
      dockerfile: Dockerfile
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - '${PORT:-3000}:${PORT:-3000}'