FROM node:16

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json .

# Install dependencies based on the preferred package manager
RUN npm ci

COPY . .
# copy required files
# COPY src ./src
# COPY prisma ./prisma
# COPY test ./test
# COPY tsconfig.json .
# COPY tsconfig.build.json .
# COPY nest-cli.json .
# COPY .env .


# generate prisma client
RUN npm run prisma:generate
