FROM node:16

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json .

# Install dependencies based on the preferred package manager
RUN npm ci

COPY . .

# generate prisma client
RUN npm run prisma:generate
